
name: Update files in s3 bucket

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  upload_s3_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install pip and pelican
        run: sudo apt update
        run: sudo apt install python3-pip
        run: pip install pelican

      # Upload s3 files
      - name: Run make S3_upload
        run: make s3_upload
