
name: Update files in s3 bucket

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check if pip installed:
    runs-on: ubuntu-latest

    steps:
      - uses: which pip
      - uses: sudo apt update
      - uses: sudo apt install python3-pip
      - uses: pip install pelican


      
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run make S3_upload
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
